Tracking
talos-rit/camera_arm pull request #27
Opened 2024-10-08 18:30 UTC by nolanporter77

Adding implemented algorithm for person detecting and tracking.

2024-10-08 18:37 UTC, DevanTurtle7 requested changes
Looks good. Small nitpick.

2024-10-08 18:37 UTC, DevanTurtle7 commented on requirements.txt
> +argparse
Thanks for keeping this updated. Can you include the versions as well? You can just run:

```
pip freeze > requirements.txt
```

2024-10-08 21:58 UTC, DevanTurtle7 approved these changes

2024-10-10 16:47 UTC, merged

2024-12-05 20:52 UTC, nolanporter77 commented
PR Confidence: 3 
Tracking works but not sure if this is our final tracker